blank_issues_enabled: true
contact_links:
  - name: Discuss Chocolate Bar on the Discord server.
    url: https://discord.gg/SN89y7EQTN
    about: Discuss bug reports, suggestions or other AE related stuff on our Discord server.